In [2]:
import numpy

In [3]:
numpy.array([2,3,5])

array([2, 3, 5])

In [4]:
import numpy as np

In [5]:
np.array([3,5,6])

array([3, 5, 6])

In [8]:
import numpy as np
np.array(a)

array([1, 2, 3])

In [9]:
a

[1, 2, 3]

In [10]:
c=np.array(b)*np.array(a)

In [11]:
c

array([ 1,  8, 27])

In [12]:
import numpy as np
p=np.array([[2,5,6],[1,2,3]])
p

array([[2, 5, 6],
       [1, 2, 3]])

In [13]:
q=np.array([[2,5],[1,2],[2,2]])
print(p)
print(q)

[[2 5 6]
 [1 2 3]]
[[2 5]
 [1 2]
 [2 2]]


In [14]:
a=p.dot(q)
print(a)


[[21 32]
 [10 15]]


In [15]:
% 2D array

UsageError: Line magic function `%` not found.


In [16]:
np_a=np.array([[2,3,4],[4,9,16]])

In [17]:
np_a

array([[ 2,  3,  4],
       [ 4,  9, 16]])

In [18]:
np_a.shape

(2, 3)

In [19]:
np_a[0][2]

4

In [20]:
np_a[0:1]

array([[2, 3, 4]])