In [1]:
#numpy is used for array computation

In [2]:
import numpy as np


In [3]:
np.array([2,4,8])

array([2, 4, 8])

In [4]:
a=np.array([2,4,8])

In [5]:
a

array([2, 4, 8])

In [6]:
print(a)

[2 4 8]


In [7]:
a[0]

2

In [8]:
L=range(4)

In [9]:
L

range(0, 4)

In [10]:
L=range(1000)

In [11]:
%timeit [i**2 for i in L]

363 µs ± 1.96 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [12]:
a.shape

(3,)

In [13]:
len(a)

3

In [14]:
# 2D Array

b=np.array([[1,2,3],[4,5,6]])

In [15]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
print(b.shape)

(2, 3)


In [17]:
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[1,2,3],[4,5,6]])
print(b+c)

[[ 2  4  6]
 [ 8 10 12]]


In [18]:
print(b*c)

[[ 1  4  9]
 [16 25 36]]


In [19]:
# practical purpose
d=np.arange(10)

In [20]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
d=np.arange(1,9,2)

In [22]:
d

array([1, 3, 5, 7])

In [23]:
d=np.arange(1,9,(2+1))

In [24]:
d

array([1, 4, 7])

In [25]:
e=np.linspace(0,1,6)

In [26]:
e

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [27]:
e=np.linspace(1,20,4)

In [28]:
e

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [29]:
x=np.ones((3,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
y=np.diag(np.array([1,2,3]))

In [31]:
y

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [32]:
p=np.random.rand(4)
p

array([0.2599938 , 0.11684287, 0.44629136, 0.82409949])

In [33]:
a=np.array([2.4,4])

In [34]:
a.dtype

dtype('float64')

In [35]:
# Slicing

In [36]:
a=np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a[-2]

8

In [38]:
a[1:7]

array([1, 2, 3, 4, 5, 6])

In [39]:
a[::5]

array([0, 5])

In [40]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [41]:
a[1::5]

array([1, 6])

In [42]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [46]:
b=range(10)

In [47]:
b

range(0, 10)

In [48]:
a==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [49]:
a.min()

0

In [50]:
a.max()

9

In [51]:
x.mean()

1.0

In [52]:
np.median(x)

1.0

In [53]:
import numpy as np
a=np.array([[1,3,4],[4,5,6]])

In [54]:
a.T

array([[1, 4],
       [3, 5],
       [4, 6]])